#!/bin/bash

VERSION="0.20.21"
MYBASENAME=$(basename "$0")

char1=$'\x01'
char2=$'\x02'
char3=$'\x03'
stopper="${char1}${char2}${char3}${char2}${char1}"

show_usage() {
    cat << EOF

Usage: $MYBASENAME <text> [<delimiter>]

Returns the amount of tokens in a <text> split by <delimiter>.

Parameters:
  text        - The string to search in (can be passed via pipe)
  delimiter   - can consist of multiple characters, defaults to space.

Examples:
  $MYBASENAME "bla bla bla"                 # -> 3 
  $MYBASENAME "bla bla bla" "l"             # -> 4
  $MYBASENAME "bla bla bla" "bla"           # -> 4 (not 2)
  $MYBASENAME "bla" "bla"                   # -> 2
  
  echo "bla bla bla" | $MYBASENAME          # -> 3
  
  #count how manny lines are in a file:
  cat file | CHOP | $MYBASENAME $'\n'
  
  #count how manny words are in a file:
  cat file | CHOP | REPLACE $'\n' ' ' | COLLAPSE | $MYBASENAME 

Options:
  -h, --help           Show this help message
  -v, --version        Show version information
  
  in case you want --help, --version or -- itself as an argument:
  --                   End of options 
          
;°)
  
EOF
}

# check only voor verbose & debug first.
verbose=""
debug=""
for arg in "$@"; do
    [ "$arg" = "--" ] && break
    if [ "$arg" = "--verbose" ]; then
        verbose=1
        break
    fi
    if [ "$arg" = "--debug" ]; then
        set -x
        break
    fi
done

MAPFILE() {
    
    # Gebruik:
    # haystack="-1--test-3-"
    # delimiter="--"
    # MAPFILE "$haystack" "$delimiter" "fields" 
    # for (( i=0; i<${#fields[@]}; i++ )); do
    #     echo "$i : '${fields[$i]}'"
    # done
    
    # Check of er een array naam is meegegeven
    if [[ -z "$3" ]]; then
        echo "MYBASENAME: ERROR in function ${0##*/}: No array name given." >&2
        exit 123
    fi
    
    local string="$1"
    local delimiter="$2"
    local -n output_array="$3"  # nameref naar array
    
    [ -n "$debug" ] && echo 
    [ -n "$debug" ] && echo "function MAPFILE"
    [ -n "$debug" ] && echo 
    [ -n "$debug" ] && echo "string : $string"
    [ -n "$debug" ] && echo "delimiter : =>$delimiter<="
    [ -n "$debug" ] && echo "output_array : $output_array"
    
    output_array=()
    local current=""
    local abc=0
    local dlen=${#delimiter}
    local slen=${#string}
    local bcd=1  # start op index 1
    
    while [[ $abc -lt $slen ]]; do
        # Check if we have delimiter at position i
        if [[ "${string:$abc:$dlen}" == "$delimiter" ]]; then
            output_array["$bcd"]="$current"
            current=""
            ((abc += dlen))
            ((bcd++))
        else
            current+="${string:$abc:1}"
            ((abc++))
        fi
    done

    output_array["$bcd"]="$current"
    ((bcd++))
    
    [ -n "$debug" ] && echo 
    [ -n "$debug" ] && echo "aantal : ${#output_array[@]}" 
    if [ -n "$debug" ] ; then
      for (( abc=1; abc<=${#output_array[@]}; abc++ )); do
        echo "$abc : '${output_array[$abc]}'"
      done
    fi
   
}

AMOUNT() {
    
    [ -n "$debug" ] && echo 
    [ -n "$debug" ] && echo "function AMOUNT"
    
    local haystack="$1"
    local delimiter="${2:- }"
    local count=0
    local fields=()
    
    [ -n "$debug" ] && echo "haystack : $haystack"
    [ -n "$debug" ] && echo "delimiter : $delimiter"
    
    #mapfile -d "$delimiter" -t fields <<< "$haystack""$stopper"
    
    # Split op delimiter 
    MAPFILE "$haystack" "$delimiter" "fields"
    
    [ -n "$debug" ] && echo 
    echo "${#fields[@]}"
    
}

# MAIN 
args=()

#
# Check voor pipe input
if IFS='' read -t 0.1 -r -n 1 eerste_karakter; then
    # Er is daadwerkelijk data. Lees de rest, voeg de marker toe en knip 'm er weer af. (grab the newline)
    rest=$(cat; echo "$stopper")
    stdin_content="${eerste_karakter}${rest}"
    # Verwijder marker + eventuele newline
    stdin_content="${stdin_content%$stopper}"
    stdin_content="${stdin_content%$'\n'}"
    # we willen "" ook vangen.
    # if [ -n "$stdin_content" ]; then
        args+=("$stdin_content")
    # fi
# else
  # # pipe or file
  # # bacon (en anderen) openen een pipe intern. beiden (-p en -f ) reageren daarop.
  # if [ -p /dev/stdin ] || [ -f /dev/stdin ] ; then
  #   stdin_content=$(cat; echo "$stopper")
  #   stdin_content="${stdin_content%$stopper}"
  #   stdin_content="${stdin_content%$'\n'}"
  #   # we willen "" ook vangen.
  #   # if [ -n "$stdin_content" ]; then
  #       args+=("$stdin_content")
  #   # fi
 #  fi
fi

[ -n "$verbose" ] && echo
endofoptions=""
for arg in "$@"; do
   
    [ -n "$verbose" ] && echo "arg : $arg"
    
    case "$arg" in
        
        -h|--help)
            
            if [ -z "$endofoptions" ]; then
              show_usage
              exit 0
            fi
            args+=("$arg")
            ;;
        
        -v|--version)
            if [ -z "$endofoptions" ]; then
              echo "$VERSION"
              exit 0
            fi
            args+=("$arg")
            ;;
        
        -v|--verbose|-d|--debug)
        
           if [ -n "$endofoptions" ]; then args+=("$arg") ; fi
           ;;
            
        --)
            if [ -z "$endofoptions" ]; then
              shift
              endofoptions="1" 
              endofoptionstoggle="1"
            else
              args+=("$arg")
            fi
            ;;
                
    #    -*)
    #        # what about a megative number ?
    #        if [ -z "$endofoptions" ]; then
    #          args+=("$arg")
    #        else
    #          echo "$MYBASENAME: Unknown option $arg" >&2
    #          exit 123
    #        fi
    #        ;;
          
        *) 
            args+=("$arg")
            ;;
    esac
    
done

if [ -n "$verbose" ] ; then
  echo
  echo "number of arguments : ${#args[@]}"
  echo "stdin_content : $stdin_content"
  for ((abc=0; abc<${#args[@]}; abc++)); do
    echo "argument $abc : ${args[$((abc))]}"
  done
  echo
fi

# Valideer aantal argumenten
if [ "${#args[@]}" -lt 1 ]; then
    echo "0"
    exit 0
fi

if [ "${#args[@]}" -gt 3 ]; then
    echo "$MYBASENAME: Too many arguments" >&2
    # show_usage
    exit 123
fi

AMOUNT "${args[@]}"
retval="$?"
[ -n "$debug" ] && echo 
exit "$retval"
