#!/bin/bash

VERSION="0.20.9"
MYBASENAME=$(basename "$0")

char1=$'\x01'
char2=$'\x02'
char3=$'\x03'
stopper="${char1}${char2}${char3}${char2}${char1}"

show_usage() {
    cat << EOF

Usage: $MYBASENAME <text> [<delimiter>]

Returns the amount of tokens in a <text> split by <delimiter>.

Parameters:
  text        - The string to search in (can be passed via pipe)
  delimiter   - can consist of multiple characters, defaults to space.

Examples:
  $MYBASENAME "bla bla bla"                 # -> 3 
  $MYBASENAME "bla bla bla" "l"             # -> 4
  $MYBASENAME "bla bla bla" "bla"           # -> 4 (not 2)
  $MYBASENAME "bla" "bla"                   # -> 2
  
  echo "bla bla bla" | $MYBASENAME          # -> 3
  
  #count how manny lines are in a file:
  cat file | CHOP | $MYBASENAME $'\n'
  
  #count how manny words are in a file:
  cat file | CHOP | REPLACE $'\n' ' ' | COLLAPSE | $MYBASENAME 

Options:
  -h, --help     Show this help message
  -v, --version  Show version information

EOF
}

AMOUNT() {
    
    local haystack="$1"
    local delimiter="${2:- }"
    local count=0
    local fields=()
    
    mapfile -d "$delimiter" -t fields <<< "$haystack""$stopper"
    
    # Na het splitten, 
    if [ "${#fields[@]}" -gt 0 ]; then
        last=${#fields[@]}-1
        if [ "${fields[$last]: -5}" = "$stopper" ]; then
          fields[$last]="${fields[$last]%?????}"  # Verwijder laatste 5 karakters
        else
          fields[$last]="${fields[$last]%??????}"  # Verwijder laatste 6 karakters, incl newline
        fi
    fi
   
    # Tel hoe vaak needle voorkomt als heel veld
    # for field in "${fields[@]}"; do
    #     ((count++))
    #    #  if [ -n "$debug" ] && echo "$count : $field"
    # done
    
    # echo "$count"
    
    echo "${#fields[@]}"
    
}

# MAIN 
args=()

# Check voor pipe input
# Vervang de hele check door dit blok
if read -t 0.01 -r -n 1 eerste_karakter; then
    # Er is daadwerkelijk data. Lees de rest, voeg de marker toe en knip 'm er weer af.
    rest=$(cat; echo "$stopper")
    stdin_content="${eerste_karakter}${rest}"
    # Verwijder marker + eventuele newline
    stdin_content="${stdin_content%$stopper}"
    stdin_content="${stdin_content%$'\n'}"
    # we willen "" ook vangen.
    # if [ -n "$stdin_content" ]; then
        args+=("$stdin_content")
    # fi
fi

debug=""
verbose=""
dryrun=""
silent=""
endofoptions=""
for arg in "$@"; do
    case "$arg" in
        
        -h|--help)
            
            if [ -z "$endofoptions" ]; then
              show_usage
              exit 0
            fi
            args+=("$arg")
            ;;
        
        -v|--version)
            if [ -z "$endofoptions" ]; then
              echo "$VERSION"
              exit 0
            fi
            args+=("$arg")
            ;;
           
        -d|--debug)
            if [ -z "$endofoptions" ]; then
              debug="1"
            else
              args+=("$arg")
            fi
            ;;
        
        --verbose)
            if [ -z "$endofoptions" ]; then
              verbose="1"
            else
              args+=("$arg")
            fi
            ;;
        
        --dryrun)
            if [ -z "$endofoptions" ]; then
              dryrun="1"
            else
              args+=("$arg")
            fi
            ;;
        
        -s|--silent)
            if [ -z "$endofoptions"]; then
              silent="1"
            else
              args+=("$arg")
            fi
            ;;
        
        
        --)
            if [ -z "$endofoptions" ]; then
              shift
              endofoptions="1"  
            else
              args+=("$arg")
            fi
            ;;
                
        -*)
            if [ -z "$endofoptions" ]; then
              args+=("$arg")
            else
              echo "ERROR: Unknown option $arg" >&2
              show_usage
              exit 123
            fi
            ;;
          
        *) 
            args+=("$arg")
            ;;
    esac
done

# Check bash versie (mapfile bestaat sinds bash 4.0)
if [ "${BASH_VERSINFO[0]}" -lt 4 ]; then
  echo "Warning: Your bash version is ${BASH_VERSINFO[0]}.${BASH_VERSINFO[1]}" >&2
  echo "mapfile needs bash 4.0 or higher. Upgrade bash for full support." >&2
  exit 123
fi

# Valideer aantal argumenten
if [ "${#args[@]}" -lt 1 ]; then
    echo "ERROR: Need at least some text." >&2
    # show_usage
    exit 123
fi

if [ "${#args[@]}" -gt 3 ]; then
    echo "ERROR: Too many arguments" >&2
    # show_usage
    exit 123
fi

AMOUNT "${args[@]}"
exit $?
