#!/bin/bash

VERSION="0.20.5"
MYBASENAME=$(basename "$0")

char1=$'\x01'
char2=$'\x02'
char3=$'\x03'
stopper="${char1}${char2}${char3}${char2}${char1}"

show_usage() {
    cat << EOF

Usage: $MYBASENAME [<string>] [<delimiter>]

Returns the ASCII/Unicode values of all characters.
If no string argument is given, reads from stdin.

Parameters:
  string      - Optional: string to convert (reads from stdin if omitted)
  delimiter   - Optional: character(s) to place between values (default: space)

Examples:
  $MYBASENAME "abc"              # -> 97 98 99 (space separated)
  $MYBASENAME "abc" ','          # -> 97,98,99 (comma separated)
  echo "Hello" | $MYBASENAME ' ' # -> 72 101 108 108 111
  $MYBASENAME $'a\nb'            # -> 97 10 98

Options:
  -h, --help     Show this help message
  -v, --version  Show version information

EOF
}

ASC() {
    local input="$1"
    local delimiter="${2:-$' '}"
    local char=""
    local i
    local first=1
    
    # Loop door alle karakters
    for ((i=0; i<${#input}; i++)); do
        char="${input:$i:1}"
        if [ $first -eq 1 ]; then
            printf "%d" "'$char"
            first=0
        else
            printf "%s%d" "$delimiter" "'$char"
        fi
    done
    
    # Alleen een newline aan het einde als er output was
    if [ $first -eq 0 ]; then
        echo
    fi
}

# MAIN 
args=()

# Check voor pipe input
# Vervang de hele check door dit blok
if read -t 0.01 -r -n 1 eerste_karakter; then
    # Er is daadwerkelijk data. Lees de rest, voeg de marker toe en knip 'm er weer af.
    rest=$(cat; echo "$stopper")
    stdin_content="${eerste_karakter}${rest}"
    # Verwijder marker + eventuele newline
    stdin_content="${stdin_content%$stopper}"
    stdin_content="${stdin_content%$'\n'}"
    # we willen "" ook vangen.
    # if [ -n "$stdin_content" ]; then
        args+=("$stdin_content")
    # fi
fi

debug=""
verbose=""
dryrun=""
silent=""
endofoptions=""
for arg in "$@"; do
    case "$arg" in
        
        -h|--help)
            
            if [ -z "$endofoptions" ]; then
              show_usage
              exit 0
            fi
            args+=("$arg")
            ;;
        
        -v|--version)
            if [ -z "$endofoptions" ]; then
              echo "$VERSION"
              exit 0
            fi
            args+=("$arg")
            ;;
           
        -d|--debug)
            if [ -z "$endofoptions" ]; then
              debug="1"
            else
              args+=("$arg")
            fi
            ;;
        
        --verbose)
            if [ -z "$endofoptions" ]; then
              verbose="1"
            else
              args+=("$arg")
            fi
            ;;
        
        --dryrun)
            if [ -z "$endofoptions" ]; then
              dryrun="1"
            else
              args+=("$arg")
            fi
            ;;
        
        -s|--silent)
            if [ -z "$endofoptions"]; then
              silent="1"
            else
              args+=("$arg")
            fi
            ;;
        
        
        --)
            if [ -z "$endofoptions" ]; then
              shift
              endofoptions="1"  
            else
              args+=("$arg")
            fi
            ;;
                
        -*)
            if [ -z "$endofoptions" ]; then
              args+=("$arg")
            else
              echo "ERROR: Unknown option $arg" >&2
              show_usage
              exit 123
            fi
            ;;
          
        *) 
            args+=("$arg")
            ;;
    esac
done

# Valideer aantal argumenten
if [ "${#args[@]}" -gt 2 ]; then
    echo >&2
    echo "ERROR: Too many arguments" >&2
    # show_usage
    exit 123
fi

if [ "${#args[@]}" -lt 1 ]; then
    echo >&2
    echo "ERROR: Too few arguments" >&2
    # show_usage
    exit 123
fi

ASC "${args[@]}"
exit $?
