#!/bin/bash

VERSION="0.20.7"
MYBASENAME=$(basename "$0")

char1=$'\x01'
char2=$'\x02'
char3=$'\x03'
stopper="${char1}${char2}${char3}${char2}${char1}"

show_usage() {
    cat << EOF

Usage: $MYBASENAME <number> [<number> ...]

Returns the ASCII character(s) for given value(s).
If no arguments are given, reads numbers from stdin (space-separated).
If both stdin and arguments are given, all numbers are combined.

Examples:
  $MYBASENAME 97                            # -> a
  $MYBASENAME 10                            # -> (newline)
  $MYBASENAME 65 66 67                      # -> ABC
  echo "98 108 97" | $MYBASENAME            # -> bla
  echo "98 108 97" | $MYBASENAME 98 108 97  # -> blabla
  echo bla | ASC | $MYBASENAME 98 108 97    # -> blabla

Options:
  -h, --help           Show this help message
  -v, --version        Show version information
  
  in case you want --help, --version or -- itself as an argument:
  --                   End of options 
          
;°)
  
EOF
}

# check only voor verbose & debug first.
verbose=""
debug=""
for arg in "$@"; do
    [ "$arg" = "--" ] && break
    if [ "$arg" = "--verbose" ]; then
        verbose=1
        break
    fi
    if [ "$arg" = "--debug" ]; then
        set -x
        break
    fi
done

CHR() {
    
    local num
    local amount_arguments
    local amount_words
    local abc
    local line
    local word
    
    amount_arguments="${#args[@]}"
    
    for (( abc=0; abc<"$amount_arguments";abc++ )); do
      for num in ${args["$abc"]} ; do
        if [[ ! "$num" =~ ^[0-9]+$ ]] || [ "$num" -lt 0 ] || [ "$num" -gt 255 ]; then
            echo "$MYBASENAME: '$num' is not a valid ASCII value (0-255)" >&2
            exit 123
        fi
        # Converteer nummer naar karakter
        printf -v char "\\x$(printf "%x" "$num")"
        result+="$char"
      done
    done
    
    if [ -n "$result" ] ; then
      echo "$result"
    fi
    
}

# MAIN 
args=()

#
# Check voor pipe input
if IFS='' read -t 0.01 -r -n 1 eerste_karakter; then
    # Er is daadwerkelijk data. Lees de rest, voeg de marker toe en knip 'm er weer af. (grab the newline)
    rest=$(cat; echo "$stopper")
    stdin_content="${eerste_karakter}${rest}"
    # Verwijder marker + eventuele newline
    stdin_content="${stdin_content%$stopper}"
    stdin_content="${stdin_content%$'\n'}"
    # we willen "" ook vangen.
    # if [ -n "$stdin_content" ]; then
        args+=("$stdin_content")
    # fi
# else
  # # pipe or file
  # # bacon (en anderen) openen een pipe intern. beiden (-p en -f ) reageren daarop.
  # if [ -p /dev/stdin ] || [ -f /dev/stdin ] ; then
  #   stdin_content=$(cat; echo "$stopper")
  #   stdin_content="${stdin_content%$stopper}"
  #   stdin_content="${stdin_content%$'\n'}"
  #   # we willen "" ook vangen.
  #   # if [ -n "$stdin_content" ]; then
  #       args+=("$stdin_content")
  #   # fi
 #  fi
fi

debug=""
endofoptions=""
for arg in "$@"; do

    case "$arg" in
        
        -h|--help)
            
            if [ -z "$endofoptions" ]; then
              show_usage
              exit 0
            fi
            args+=("$arg")
            ;;
        
        -v|--version)
            if [ -z "$endofoptions" ]; then
              echo "$VERSION"
              exit 0
            fi
            args+=("$arg")
            ;;
           
        -d|--debug)
            if [ -z "$endofoptions" ]; then
              debug="1"
            else
              args+=("$arg")
            fi
            ;;
        
        --)
            if [ -z "$endofoptions" ]; then
              shift
              endofoptions="1" 
              endofoptionstoggle="1"
            else
              args+=("$arg")
            fi
            ;;
                
    #    -*)
    #        # what about a megative number ?
    #        if [ -z "$endofoptions" ]; then
    #          args+=("$arg")
    #        else
    #          echo "$MYBASENAME: Unknown option $arg" >&2
    #          exit 123
    #        fi
    #        ;;
          
        *) 
            args+=("$arg")
            ;;
    esac
    
done

CHR "${args[@]}"
exit $?
