#!/bin/bash

# set -x  # Toont elke regel voor uitvoering
# set -e  # Stopt bij eerste fout

VERSION="0.1.3"
MYBASENAME=$(basename "$0")
SCRIPTNAME="$MYBASENAME"

char1=$'\x01'
char2=$'\x02'
char3=$'\x03'
stopper="${char1}${char2}${char3}${char2}${char1}"

show_usage() {
    cat << EOF
    
Usage: $MYBASENAME [option] <folder> | <device>

Returns the amount of free space left on a <folder> or <device>.

Examples:
  $MYBASENAME "${HOME}/Documents"

Options:
  -h, --help           Show this help message
  -v, --version        Show version information
  --                   End of options 
          
;°)
  
EOF
}

# check only voor verbose & debug first.
verbose=""
debug=""
for arg in "$@"; do
    [ "$arg" = "--" ] && break
    [ "$arg" = "--verbose" ] && verbose=1
    [ "$arg" = "--debug" ] && set -x
done

# Cross-platform versie (werkt ook op macOS)
if command -v readlink >/dev/null 2>&1 && readlink -f . >/dev/null 2>&1; then
    SCRIPTPATH="$(readlink -f "${BASH_SOURCE[0]}")"
else
    # Fallback voor macOS (gebruik cd + pwd truc)
    SCRIPTPATH="$( cd "$(dirname "${BASH_SOURCE[0]}")" && pwd )/$(basename "${BASH_SOURCE[0]}")"
fi

SCRIPTDIR="$(dirname "$SCRIPTPATH")"
if [ "$(basename "$SCRIPTDIR")" = "BIN" ] ||  [ "$(basename "$SCRIPTDIR")" = "SRC" ] || [ "$(basename "$SCRIPTDIR")" = "MUSEUM" ] ; then
  DIRECTORY="$(dirname "$SCRIPTDIR")"
else
  DIRECTORY="$SCRIPTDIR"
fi

MAPFILE() {
    
    # Gebruik:
    # haystack="-1--test-3-"
    # delimiter="--"
    # MAPFILE "$haystack" "$delimiter" "fields" 
    # for (( i=0; i<${#fields[@]}; i++ )); do
    #     echo "$i : '${fields[$i]}'"
    # done
    
    # Check of er een array naam is meegegeven
    if [[ -z "$3" ]]; then
        echo "MYBASENAME: ERROR in function ${0##*/}: No array name given." >&2
        exit 123
    fi
    
    local string="$1"
    local delimiter="$2"
    local -n output_array="$3"  # nameref naar array
    
    [ -n "$verbose" ] && echo 
    [ -n "$verbose" ] && echo "function MAPFILE"
    [ -n "$verbose" ] && echo 
    [ -n "$verbose" ] && echo "string : $string"
    [ -n "$verbose" ] && echo "delimiter : =>$delimiter<="
    [ -n "$verbose" ] && echo "output_array : $output_array"
    
    output_array=()
    local current=""
    local abc=0
    local dlen=${#delimiter}
    local slen=${#string}
    local bcd=1  # start op index 1
    
    while [[ $abc -lt $slen ]]; do
        # Check if we have delimiter at position i
        if [[ "${string:$abc:$dlen}" == "$delimiter" ]]; then
            output_array["$bcd"]="$current"
            current=""
            ((abc += dlen))
            ((bcd++))
        else
            current+="${string:$abc:1}"
            ((abc++))
        fi
    done

    output_array["$bcd"]="$current"
    ((bcd++))
    
    [ -n "$verbose" ] && echo 
    [ -n "$verbose" ] && echo "aantal : ${#output_array[@]}" 
    if [ -n "$verbose" ] ; then
      for (( abc=1; abc<=${#output_array[@]}; abc++ )); do
        echo "$abc : '${output_array[$abc]}'"
      done
    fi
   
}

FREE(){
  
  # [ -n "$verbose" ] || [ -n "$dryrun" ] && echo
  # [ -n "$verbose" ] || [ -n "$dryrun" ] && echo ":"
  # [ -n "$verbose" ] || [ -n "$dryrun" ] && echo
  # [ -n "$dryrun" ] && exit 0
  # :
  
  df="$(df -h "$1")"
  retval="$?"
  if [ "$retval" = "0" ] ; then
    df="$(TOKEN "$df" "2" $'\n')"
    df="$(COLLAPSE "$df")"
    df="$(TOKEN "$df" "4")"
    unit="$(CHAR "$df" "-1")"
    df="$(RIP "$df" "-1")"
    echo "$df"" ""$unit"
    return 0
  fi
  
  echo "$df" >&2
  return "$retval"
    
}

 
# MAIN 
args=()

# Check voor pipe input
if IFS='' read -t 0.01 -r -n 1 eerste_karakter; then
    # Er is daadwerkelijk data. Lees de rest, voeg de marker toe en knip 'm er weer af. (grab the newline)
    rest=$(cat; echo "$stopper")
    stdin_content="${eerste_karakter}${rest}"
    # Verwijder marker + eventuele newline
    stdin_content="${stdin_content%$stopper}"
    stdin_content="${stdin_content%$'\n'}"
    # we willen "" ook vangen.
    # if [ -n "$stdin_content" ]; then
        args+=("$stdin_content")
    # fi
 else
   # pipe or file
   # bacon (en anderen) openen een pipe intern. beiden (-p en -f ) reageren daarop. (f°ck bacon)
   if [ -p /dev/stdin ] || [ -f /dev/stdin ] ; then
     stdin_content=$(cat; echo "$stopper")
     stdin_content="${stdin_content%$stopper}"
     stdin_content="${stdin_content%$'\n'}"
   #   we willen "" ook vangen.
   #   if [ -n "$stdin_content" ]; then
         args+=("$stdin_content")
   #   fi
   fi
  
fi

[ -n "$verbose" ] && echo
endofoptions=""
for arg in "$@"; do
   
    [ -n "$verbose" ] && echo "arg : $arg"
    
    case "$arg" in
        
        -h|--help)
            
            if [ -z "$endofoptions" ]; then
              show_usage
              exit 0
            fi
            args+=("$arg")
            ;;
        
        -v|--version)
            if [ -z "$endofoptions" ]; then
              echo "$VERSION"
              exit 0
            fi
            args+=("$arg")
            ;;
        
        --verbose|--debug)
        
           if [ -n "$endofoptions" ]; then 
             args+=("$arg") 
           fi
           
           ;;
        
        --dryrun)
            if [ -z "$endofoptions" ]; then
              dryrun=1
            else   
              args+=("$arg")
            fi
            ;;
            
        --)
            if [ -z "$endofoptions" ]; then
              shift
              endofoptions="1" 
              endofoptionstoggle="1"
            else
              args+=("$arg")
            fi
            ;;
                
    #    -*)
    #        # what about a megative number ?
    #        if [ -z "$endofoptions" ]; then
    #          args+=("$arg")
    #        else
    #          echo "$MYBASENAME: Unknown option $arg" >&2
    #          exit 123
    #        fi
    #        ;;
          
        *) 
            args+=("$arg")
            ;;
    esac
    
done

if [ -n "$verbose" ] ; then
  echo
  echo "number of arguments : ${#args[@]}"
  echo "stdin_content : =>$stdin_content<="
  for ((abc=0; abc<${#args[@]}; abc++)); do
    echo "argument $abc : =>${args[$((abc))]}<="
  done
  echo
fi


if [ "${#args[@]}" -lt "1" ] ; then
  echo >&2
  echo "$MYBASENAME: No argument provided." >&2
  echo  >&2
  exit 123
fi

if [ "${#args[@]}" -gt "1" ] ; then
  echo >&2
  echo "$MYBASENAME: Too manny arguments." >&2
  echo  >&2
  exit 123
fi

FREE "${args[@]}"
retval="$?"
[ -n "$debug" ] && echo 
exit "$retval"
