#!/bin/bash

VERSION="0.3.17"
MYBASENAME=$(basename "$0")

show_usage() {

cat << EOF

Usage: $MYBASENAME <argument>

Exits true (0) if argument is a legitimate integer, else false (1).
 
Examples:
  $MYBASENAME 123 ; echo \$?
  echo 123 | $MYBASENAME ; echo \$?
  if $MYBASENAME "3" ; then echo "yes" ; fi
  [ $MYBASENAME "abc" ] && echo "yes"
  
Options:
  -h, --help           Show this help message.
  -v, --version        Show version information.
  --                   End of options 
          
;°)
 
EOF
}

# check only voor verbose & debug first.
verbose=""
debug=""
for arg in "$@"; do
    [ "$arg" = "--" ] && break
    [ "$arg" = "--verbose" ] && verbose=1
    [ "$arg" = "--debug" ] && set -x
done

if [ -n "$verbose" ] ; then
  echo
  echo "$MYBASENAME"
  echo
  echo "All arguments one by one:"
  abc=1
  for arg in "$@"; do
    echo "$abc : $arg"
    ((abc ++))
  done
fi  

# ISINT() {
#     [[ "$1" =~ ^[0-9]+$ ]]
# }

# ISINT is wat complexer in POSIX:
ISINT() {
    case "${1#-}" in
        ''|*[!0-9]*) return 1 ;;
        *) return 0 ;;
    esac
}

# MAIN 
args=()
stdin_content=""
# Check voor pipe input
if IFS='' read -t 0.01 -r -n 1 eerste_karakter; then
    # Er is daadwerkelijk data. Lees de rest, voeg de marker toe en knip 'm er weer af. (grab the newline)
    rest=$(cat; echo "$stopper")
    stdin_content="${eerste_karakter}${rest}"
    # Verwijder marker + eventuele newline
    stdin_content="${stdin_content%$stopper}"
    stdin_content="${stdin_content%$'\n'}"
    # we willen "" toch NIET vangen.
    if [ -n "$stdin_content" ]; then
      args+=("$stdin_content")
    fi
 else
   # pipe or file
   # bacon (en anderen) openen een pipe intern. beiden (-p en -f ) reageren daarop. (f°ck bacon)
   if [ -p /dev/stdin ] || [ -f /dev/stdin ] ; then
     stdin_content=$(cat; echo "$stopper")
     stdin_content="${stdin_content%$stopper}"
     stdin_content="${stdin_content%$'\n'}"
     # we willen "" toch NIET vangen.
     if [ -n "$stdin_content" ]; then
       args+=("$stdin_content")
     fi
   fi
fi

[ -n "$verbose" ] && echo
endofoptions=""
for arg in "$@"; do
   
    [ -n "$verbose" ] && echo "arg : $arg"
    
    case "$arg" in
        
        -h|--help)
            
            if [ -z "$endofoptions" ]; then
              show_usage
              exit 0
            fi
            args+=("$arg")
            ;;
        
        -v|--version)
            if [ -z "$endofoptions" ]; then
              echo "$VERSION"
              exit 0
            fi
            args+=("$arg")
            ;;
        
        --verbose|--debug)
        
           if [ -n "$endofoptions" ]; then 
             args+=("$arg") 
           fi
           
           ;;
        
        --dryrun)
            if [ -z "$endofoptions" ]; then
              dryrun=1
            else   
              args+=("$arg")
            fi
            ;;
            
        --)
            if [ -z "$endofoptions" ]; then
              shift
              endofoptions="1" 
              endofoptionstoggle="1"
            else
              args+=("$arg")
            fi
            ;;
                
    #    -*)
    #        # what about a megative number ?
    #        if [ -z "$endofoptions" ]; then
    #          args+=("$arg")
    #        else
    #          echo "$MYBASENAME: Unknown option $arg" >&2
    #          exit 123
    #        fi
    #        ;;
          
        *) 
            args+=("$arg")
            ;;
    esac
    
done

if [ ! "${#args[@]}" = "1" ];  then 
  echo >&2
  echo "ERROR! Wrong number of arguments." >&2
  echo "try $MYBASENAME --help" >&2
  exit 123
fi

ISINT "${args[0]}"
retval="$?"

# if ! [ "$quiet" = "1" ] ; then
#   if [ "$retval" = "0" ] ; then
#     echo "true"
#   else
#     echo "false"
#   fi
# fi

exit "$retval"
