#!/bin/bash

VERSION="0.20.13"
MYBASENAME=$(basename "$0")

char1=$'\x01'
char2=$'\x02'
char3=$'\x03'
stopper="${char1}${char2}${char3}${char2}${char1}"

all=0
endofoptions="0"

show_usage() {
    cat << EOF

Usage: $MYBASENAME <string> <token> [<delimiter>] [<position>]

Verifies if a token occurs in a delimited string, optionally starting from <position>.
print the index of the found token
Returns 0 (true) if found, 1 (false) if not.

Parameters:
  string      - The string to search in (can be passed via pipe)
  token       - The token to look for
  delimiter   - Optional: character(s) that separate tokens (default: space)
  position    - Optional: if given, checks if token is at exact position (1-based)

Examples:
  $MYBASENAME "one two three" "two"              # -> 2 : true (0)
  $MYBASENAME "one two three" "four"             # -> false (1)
  $MYBASENAME "a,b,c,d,a,b,c,d" "c" ','          # -> 3
  $MYBASENAME "a,b,c,d,a,b,c,d" "c" ','  3       # -> 3
  $MYBASENAME "a,b,c,d,a,b,c,d" "c" ','  4       # -> 7
  echo "one two three" | $MYBASENAME "two"       # -> 2

Options:
  -h, --help           Show this help message
  -v, --version        Show version information
  
  in case you want --help, --version or -- itself as an argument:
  --                   End of options 
          
;°)
    
EOF
}

# check only voor verbose & debug first.
verbose=""
debug=""
for arg in "$@"; do
    [ "$arg" = "--" ] && break
    if [ "$arg" = "--verbose" ]; then
        verbose=1
        break
    fi
    if [ "$arg" = "--debug" ]; then
        set -x
        break
    fi
done

MAPFILE() {
    
    # Gebruik:
    # haystack="-1--test-3-"
    # delimiter="--"
    # MAPFILE "$haystack" "$delimiter" "fields" 
    # for (( i=0; i<${#fields[@]}; i++ )); do
    #     echo "$i : '${fields[$i]}'"
    # done
    
    # Check of er een array naam is meegegeven
    if [[ -z "$3" ]]; then
        echo "MYBASENAME: $MYBASENAME in function ${0##*/}: No array name given." >&2
        exit 123
    fi
    
    local string="$1"
    local delimiter="$2"
    local -n output_array="$3"  # nameref naar array
    
    [ -n "$debug" ] && echo 
    [ -n "$debug" ] && echo "function MAPFILE"
    [ -n "$debug" ] && echo 
    [ -n "$debug" ] && echo "string : $string"
    [ -n "$debug" ] && echo "delimiter : =>$delimiter<="
    [ -n "$debug" ] && echo "output_array : $output_array"
    
    output_array=()
    local current=""
    local abc=0
    local dlen=${#delimiter}
    local slen=${#string}
    local bcd=1  # start op index 1
    
    while [[ $abc -lt $slen ]]; do
        # Check if we have delimiter at position i
        if [[ "${string:$abc:$dlen}" == "$delimiter" ]]; then
            output_array["$bcd"]="$current"
            current=""
            ((abc += dlen))
            ((bcd++))
        else
            current+="${string:$abc:1}"
            ((abc++))
        fi
    done

    output_array["$bcd"]="$current"
    ((bcd++))
    
    [ -n "$debug" ] && echo 
    [ -n "$debug" ] && echo "aantal : ${#output_array[@]}" 
    if [ -n "$debug" ] ; then
      for (( abc=1; abc<=${#output_array[@]}; abc++ )); do
        echo "$abc : '${output_array[$abc]}'"
      done
    fi
   
}

ISTOKEN() {
    
    local haystack="$1"
    local token="$2"
    local delimiter="${3:- }"
    local startposition="${4:-1}"
    local tokens=()
    
    [ -n "$debug" ] && echo
    [ -n "$debug" ] && echo "function ISTOKEN"
    [ -n "$debug" ] && echo
    
    if  [[ "$debug" = "1" ]]; then
      echo "haystack : =>$haystack<="
      echo "token : =>$token<="
      echo "delimiter : =>$delimiter<="
      echo "startposition : =>$startposition<="
    fi

    # Validatie
    if [ -z "$haystack" ] || [ -z "$token" ]; then
        return 1
    fi

    if [[ ! "$startposition" =~ ^[0-9]+$ ]]; then
      echo "startposition must be an integer." >&2
      exit 123
    fi

    if [[ "$startposition" = "0" ]]; then
      all="1"
      startposition="1"
    fi

    # Split op delimiter 
    MAPFILE "$haystack" "$delimiter" "fields"
       
    # zoek in alle tokens
    for ((abc="$startposition"; abc<=${#fields[@]}; abc++)); do
    
      if [ "${fields[$abc]}" = "$token" ]; then
        echo  "$abc"
        exit 0
      fi
    done
    
    return 1
    
}

# MAIN 
args=()

#
# Check voor pipe input
if IFS='' read -t 0.01 -r -n 1 eerste_karakter; then
    # Er is daadwerkelijk data. Lees de rest, voeg de marker toe en knip 'm er weer af. (grab the newline)
    rest=$(cat; echo "$stopper")
    stdin_content="${eerste_karakter}${rest}"
    # Verwijder marker + eventuele newline
    stdin_content="${stdin_content%$stopper}"
    stdin_content="${stdin_content%$'\n'}"
    # we willen "" ook vangen.
    # if [ -n "$stdin_content" ]; then
        args+=("$stdin_content")
    # fi
# else
  # # pipe or file
  # # bacon (en anderen) openen een pipe intern. beiden (-p en -f ) reageren daarop.
  # if [ -p /dev/stdin ] || [ -f /dev/stdin ] ; then
  #   stdin_content=$(cat; echo "$stopper")
  #   stdin_content="${stdin_content%$stopper}"
  #   stdin_content="${stdin_content%$'\n'}"
  #   # we willen "" ook vangen.
  #   # if [ -n "$stdin_content" ]; then
  #       args+=("$stdin_content")
  #   # fi
 #  fi
fi

[ -n "$verbose" ] && echo
endofoptions=""
for arg in "$@"; do
   
    [ -n "$verbose" ] && echo "arg : $arg"
    
    case "$arg" in
        
        -h|--help)
            
            if [ -z "$endofoptions" ]; then
              show_usage
              exit 0
            fi
            args+=("$arg")
            ;;
        
        -v|--version)
            if [ -z "$endofoptions" ]; then
              echo "$VERSION"
              exit 0
            fi
            args+=("$arg")
            ;;
        
        -v|--verbose|-d|--debug)
        
           if [ -n "$endofoptions" ]; then args+=("$arg") ; fi
           ;;
            
        --)
            if [ -z "$endofoptions" ]; then
              shift
              endofoptions="1" 
              endofoptionstoggle="1"
            else
              args+=("$arg")
            fi
            ;;
                
    #    -*)
    #        # what about a megative number ?
    #        if [ -z "$endofoptions" ]; then
    #          args+=("$arg")
    #        else
    #          echo "$MYBASENAME: Unknown option $arg" >&2
    #          exit 123
    #        fi
    #        ;;
          
        *) 
            args+=("$arg")
            ;;
    esac
    
done

# Valideer aantal argumenten
if [ "${#args[@]}" -lt 2 ]; then
    echo "$MYBASENAME: Need at least string and token" >&2
    exit 123
fi

if [ "${#args[@]}" -gt 4 ]; then
    echo "$MYBASENAME: Too many arguments" >&2
    exit 1
fi

# Roep ISTOKEN aan
ISTOKEN "${args[@]}"
exit $?
