#!/bin/env bash

# set -x  # Toont elke regel voor uitvoering
# set -e  # Stopt bij eerste fout

VERSION="0.1.1"
MYBASENAME=$(basename "$0")
SCRIPTNAME="$MYBASENAME"

char1=$'\x01'
char2=$'\x02'
char3=$'\x03'
stopper="${char1}${char2}${char3}${char2}${char1}"

show_usage() {
    cat << EOF
    
Usage: $MYBASENAME <command> [arguments...]   

Negate the exit status of a command (wrapper around bash '!' operator)
   
EXAMPLES
    if NOT ISINT "$age"; then
       echo "Leeftijd moet een getal zijn"
    fi

OPTIONS
    -h, --help           Show this help message
    -v, --version        Show version information
    --                   End of options (useful if command starts with -)

;°)
  
EOF
}

NOT() { ! "$@"; }

# MAIN 
args=()

#
# Check voor pipe input
if read -t 0.01 -r -n 1 eerste_karakter; then
    # Er is daadwerkelijk data. Lees de rest, voeg de marker toe en knip 'm er weer af. (grab the newline)
    rest=$(cat; echo "$stopper")
    stdin_content="${eerste_karakter}${rest}"
    # Verwijder marker + eventuele newline
    stdin_content="${stdin_content%$stopper}"
    stdin_content="${stdin_content%$'\n'}"
    # we willen "" ook vangen.
    # if [ -n "$stdin_content" ]; then
        args+=("$stdin_content")
    # fi
# else
  # # pipe or file
  # # bacon (en anderen) openen een pipe intern. beiden (-p en -f ) reageren daarop.
  # if [ -p /dev/stdin ] || [ -f /dev/stdin ] ; then
  #   stdin_content=$(cat; echo "$stopper")
  #   stdin_content="${stdin_content%$stopper}"
  #   stdin_content="${stdin_content%$'\n'}"
  #   # we willen "" ook vangen.
  #   # if [ -n "$stdin_content" ]; then
  #       args+=("$stdin_content")
  #   # fi
 #  fi
fi

NOT "${args[@]}"
exit $?
