#!/bin/env bash

# set -x  # Toont elke regel voor uitvoering
# set -e  # Stopt bij eerste fout

VERSION="0.1"
MYBASENAME=$(basename "$0")
SCRIPTNAME="$MYBASENAME"

char1=$'\x01'
char2=$'\x02'
char3=$'\x03'
stopper="${char1}${char2}${char3}${char2}${char1}"

show_usage() {
    cat << EOF
    
Usage: $MYBASENAME <command> [arguments...]   

Negate the exit status of a command (wrapper around bash '!' operator)
   
EXAMPLES
    if NOT ISINT "$age"; then
       echo "Leeftijd moet een getal zijn"
    fi

OPTIONS
    -h, --help           Show this help message
    -v, --version        Show version information
    --                   End of options (useful if command starts with -)

;°)
  
EOF
}

NOT() { ! "$@"; }

# MAIN 
args=()

# Check voor pipe input
# NOT 4 NOT

verbose=""
endofoptions=""
for arg in "$@"; do

    case "$arg" in
        
        -h|--help)
            
            if [ -z "$endofoptions" ]; then
              show_usage
              exit 0
            fi
            args+=("$arg")
            ;;
        
        -v|--version)
            if [ -z "$endofoptions" ]; then
              echo "$VERSION"
              exit 0
            fi
            args+=("$arg")
            ;;
           
        -v|--verbose)
            if [ -z "$endofoptions" ]; then
              verbose="1"
            else
              args+=("$arg")
            fi
            ;;
        
        -d|--debug)
            set -x
            ;;
            
        --)
            if [ -z "$endofoptions" ]; then
              shift
              endofoptions="1" 
              endofoptionstoggle="1"
            else
              args+=("$arg")
            fi
            ;;
                
    #    -*)
    #        # what about a megative number ?
    #        if [ -z "$endofoptions" ]; then
    #          args+=("$arg")
    #        else
    #          echo "$MYBASENAME: Unknown option $arg" >&2
    #          exit 123
    #        fi
    #        ;;
          
        *) 
            args+=("$arg")
            ;;
    esac
    
done

if [ -n "$verbose" ] ; then
  echo
  echo ${#args[@]}
  for ((abc=0; abc<${#args[@]}; abc++)); do
    echo "argument $abc : ${args[$((abc))]}"
  done
  echo
fi

NOT "${args[@]}"
exit $?
