#!/bin/env bash

VERSION="0.20.3"
MYBASENAME=$(basename "$0")
SCRIPT_NAME="$MYBASENAME"

char1=$'\x01'
char2=$'\x02'
char3=$'\x03'
stopper="${char1}${char2}${char3}${char2}${char1}"

show_usage() {
    cat << EOF
    
Usage: $SCRIPT_NAME [option] <haystack> <needle> <replacement>

<haystack> can be replaced with piped input.

Substitutes ALL occurrences of <needle> in <haystack> with <replacement>.
The <needle> can be a single line or multiple lines.
The <replacement> does not need to be the same size as the substring.

Examples:
  $SCRIPT_NAME "Hello world" world "everyone"
  $SCRIPT_NAME "Some text" me 123
  echo "Hello world" | $SCRIPT_NAME world "everyone"
  
  # Multi-line replacement
  echo "line one
line two
line three
line four" | $SCRIPT_NAME  'line two
line three' 'line five
line six'

  # Replacement with newline in replacement
  echo "one,two,three" | $SCRIPT_NAME ',' $',\n'

Options:
  -v, --version     Show version
  -h, --help        Show this help message
EOF

}

REPLACE() {
    
    local haystack="$1"
    local needle="$2"
    local replacement="${3:-}"
    local result=""
    
    # Als needle leeg is, geef dan haystack terug
    if [ -z "$needle" ]; then
      if [ -n "$haystack" ]; then
        echo "$haystack"
      fi
      return 0
    fi
    
    result="${haystack//$needle/$replacement}"
    
    # Alleen output als resultaat niet leeg is
    if [ -n "$result" ]; then
        echo "$result"
    fi
    
}

# MAIN 
args=()

# Check voor pipe input
# Vervang de hele check door dit blok
if read -t 0.01 -r -n 1 eerste_karakter; then
    # Er is daadwerkelijk data. Lees de rest, voeg de marker toe en knip 'm er weer af.
    rest=$(cat; echo "$stopper")
    stdin_content="${eerste_karakter}${rest}"
    # Verwijder marker + eventuele newline
    stdin_content="${stdin_content%$stopper}"
    stdin_content="${stdin_content%$'\n'}"
    # we willen "" ook vangen.
    # if [ -n "$stdin_content" ]; then
        args+=("$stdin_content")
    # fi
fi

debug=""
verbose=""
dryrun=""
silent=""
endofoptions=""
for arg in "$@"; do
    case "$arg" in
        
        -h|--help)
            
            if [ -z "$endofoptions" ]; then
              show_usage
              exit 0
            fi
            args+=("$arg")
            ;;
        
        -v|--version)
            if [ -z "$endofoptions" ]; then
              echo "$VERSION"
              exit 0
            fi
            args+=("$arg")
            ;;
           
        -d|--debug)
            if [ -z "$endofoptions" ]; then
              debug="1"
            else
              args+=("$arg")
            fi
            ;;
        
        --verbose)
            if [ -z "$endofoptions" ]; then
              verbose="1"
            else
              args+=("$arg")
            fi
            ;;
        
        --dryrun)
            if [ -z "$endofoptions" ]; then
              dryrun="1"
            else
              args+=("$arg")
            fi
            ;;
        
        -s|--silent)
            if [ -z "$endofoptions"]; then
              silent="1"
            else
              args+=("$arg")
            fi
            ;;
        
        
        --)
            if [ -z "$endofoptions" ]; then
              shift
              endofoptions="1"  
            else
              args+=("$arg")
            fi
            ;;
                
        -*)
            if [ -z "$endofoptions" ]; then
              args+=("$arg")
            else
              echo "ERROR: Unknown option $arg" >&2
              show_usage
              exit 123
            fi
            ;;
          
        *) 
            args+=("$arg")
            ;;
    esac
done

# Valideer aantal argumenten
if [ "${#args[@]}" -lt 2 ]; then
    echo >&2
    echo "ERROR! Need at least haystack and needle" >&2
    # echo "Try $SCRIPT_NAME --help" >&2
    exit 123
fi

if [ "${#args[@]}" -gt 3 ]; then
    echo >&2
    echo "ERROR! Too many arguments" >&2
    # echo "Try $SCRIPT_NAME --help" >&2
    exit 123
fi

# Als er maar 2 argumenten zijn, is replacement leeg
if [ "${#args[@]}" -eq 2 ]; then
    args+=("")
fi

# Voer REPLACE uit
REPLACE "${args[@]}"
exit $?
