#!/bin/env bash

VERSION="0.20.6"
MYBASENAME=$(basename "$0")
SCRIPT_NAME="$MYBASENAME"

char1=$'\x01'
char2=$'\x02'
char3=$'\x03'
stopper="${char1}${char2}${char3}${char2}${char1}"

show_usage() {
    cat << EOF
    
Usage: $SCRIPT_NAME [option] <haystack> <needle> <replacement>

<haystack> can be replaced with piped input.

Substitutes ALL occurrences of <needle> in <haystack> with <replacement>.
The <needle> can be a single line or multiple lines.
The <replacement> does not need to be the same size as the substring.

Examples:
  $SCRIPT_NAME "Hello world" world "everyone"
  $SCRIPT_NAME "Some text" me 123
  echo "Hello world" | $SCRIPT_NAME world "everyone"
  
  # Multi-line replacement
  echo "line one
line two
line three
line four" | $SCRIPT_NAME  'line two
line three' 'line five
line six'

  # Replacement with newline in replacement
  echo "one,two,three" | $SCRIPT_NAME ',' $',\n'

Options:
  -h, --help           Show this help message
  -v, --version        Show version information
  
  in case you want --help, --version or -- itself as an argument:
  --                   End of options 
          
;°)
  
EOF
}

REPLACE() {
    
    local haystack="$1"
    local needle="$2"
    local replacement="${3:-}"
    local result=""
    
    # Als needle leeg is, geef dan haystack terug
    if [ -z "$needle" ]; then
      if [ -n "$haystack" ]; then
        echo "$haystack"
      fi
      return 0
    fi
    
    result="${haystack//$needle/$replacement}"
    
    # Alleen output als resultaat niet leeg is
    if [ -n "$result" ]; then
        echo "$result"
    fi
    
}

# MAIN 
args=()

#
# Check voor pipe input
if read -t 0.01 -r -n 1 eerste_karakter; then
    # Er is daadwerkelijk data. Lees de rest, voeg de marker toe en knip 'm er weer af. (grab the newline)
    rest=$(cat; echo "$stopper")
    stdin_content="${eerste_karakter}${rest}"
    # Verwijder marker + eventuele newline
    stdin_content="${stdin_content%$stopper}"
    stdin_content="${stdin_content%$'\n'}"
    # we willen "" ook vangen.
    # if [ -n "$stdin_content" ]; then
        args+=("$stdin_content")
    # fi
# else
  # # pipe or file
  # # bacon (en anderen) openen een pipe intern. beiden (-p en -f ) reageren daarop.
  # if [ -p /dev/stdin ] || [ -f /dev/stdin ] ; then
  #   stdin_content=$(cat; echo "$stopper")
  #   stdin_content="${stdin_content%$stopper}"
  #   stdin_content="${stdin_content%$'\n'}"
  #   # we willen "" ook vangen.
  #   # if [ -n "$stdin_content" ]; then
  #       args+=("$stdin_content")
  #   # fi
 #  fi
fi

debug=""
endofoptions=""
for arg in "$@"; do

    case "$arg" in
        
        -h|--help)
            
            if [ -z "$endofoptions" ]; then
              show_usage
              exit 0
            fi
            args+=("$arg")
            ;;
        
        -v|--version)
            if [ -z "$endofoptions" ]; then
              echo "$VERSION"
              exit 0
            fi
            args+=("$arg")
            ;;
           
        -d|--debug)
            if [ -z "$endofoptions" ]; then
              debug="1"
            else
              args+=("$arg")
            fi
            ;;
        
        --)
            if [ -z "$endofoptions" ]; then
              shift
              endofoptions="1" 
              endofoptionstoggle="1"
            else
              args+=("$arg")
            fi
            ;;
                
    #    -*)
    #        # what about a megative number ?
    #        if [ -z "$endofoptions" ]; then
    #          args+=("$arg")
    #        else
    #          echo "$MYBASENAME: Unknown option $arg" >&2
    #          exit 123
    #        fi
    #        ;;
          
        *) 
            args+=("$arg")
            ;;
    esac
    
done

# Valideer aantal argumenten
if [ "${#args[@]}" -lt 2 ]; then
    echo >&2
    echo "$MYBASENAME! Need at least haystack and needle" >&2
    # echo "Try $SCRIPT_NAME --help" >&2
    exit 123
fi

if [ "${#args[@]}" -gt 3 ]; then
    echo >&2
    echo "$MYBASENAME! Too many arguments" >&2
    # echo "Try $SCRIPT_NAME --help" >&2
    exit 123
fi

# Als er maar 2 argumenten zijn, is replacement leeg
if [ "${#args[@]}" -eq 2 ]; then
    args+=("")
fi

# Voer REPLACE uit
REPLACE "${args[@]}"
exit $?
