#!/bin/bash

VERSION="0.20.7"
MYBASENAME=$(basename "$0")

char1=$'\x01'
char2=$'\x02'
char3=$'\x03'
stopper="${char1}${char2}${char3}${char2}${char1}"

show_usage() {
    cat << EOF

Usage: $MYBASENAME <text> [<delimiter>]

Reverses a string. If delimiter is given, reverses tokens instead of characters.

Parameters:
  text        - The string to reverse (can be passed via pipe)
  delimiter   - Optional: if given, split into tokens and reverse their order

Examples:
  $MYBASENAME "Hello world"              # -> dlrow olleH (characters)
  $MYBASENAME "Hello world" " "          # -> world Hello (tokens)
  $MYBASENAME "one,two,three" ','        # -> three,two,one
  echo "abc" | $MYBASENAME               # -> cba
  echo "one two three" | $MYBASENAME " " # -> three two one

Options:
  -h, --help           Show this help message
  -v, --version        Show version information
  
  in case you want --help, --version or -- itself as an argument:
  --                   End of options 
          
;°)
  
EOF
}

# check only voor verbose & debug first.
verbose=""
debug=""
for arg in "$@"; do
    [ "$arg" = "--" ] && break
    if [ "$arg" = "--verbose" ]; then
        verbose=1
        break
    fi
    if [ "$arg" = "--debug" ]; then
        set -x
        break
    fi
done

MAPFILE() {
    
    # Gebruik:
    # haystack="-1--test-3-"
    # delimiter="--"
    # MAPFILE "$haystack" "$delimiter" "fields" 
    # for (( i=0; i<${#fields[@]}; i++ )); do
    #     echo "$i : '${fields[$i]}'"
    # done
    
    # Check of er een array naam is meegegeven
    if [[ -z "$3" ]]; then
        echo "MYBASENAME: $MYBASENAME in function ${0##*/}: No array name given." >&2
        exit 123
    fi
    
    local string="$1"
    local delimiter="$2"
    local -n output_array="$3"  # nameref naar array
    
    [ -n "$debug" ] && echo 
    [ -n "$debug" ] && echo "function MAPFILE"
    [ -n "$debug" ] && echo 
    [ -n "$debug" ] && echo "string : $string"
    [ -n "$debug" ] && echo "delimiter : =>$delimiter<="
    [ -n "$debug" ] && echo "output_array : $output_array"
    
    output_array=()
    local current=""
    local abc=0
    local dlen=${#delimiter}
    local slen=${#string}
    local bcd=1  # start op index 1
    
    while [[ $abc -lt $slen ]]; do
        # Check if we have delimiter at position i
        if [[ "${string:$abc:$dlen}" == "$delimiter" ]]; then
            output_array["$bcd"]="$current"
            current=""
            ((abc += dlen))
            ((bcd++))
        else
            current+="${string:$abc:1}"
            ((abc++))
        fi
    done

    output_array["$bcd"]="$current"
    ((bcd++))
    
    [ -n "$debug" ] && echo 
    [ -n "$debug" ] && echo "aantal : ${#output_array[@]}" 
    if [ -n "$debug" ] ; then
      for (( abc=1; abc<=${#output_array[@]}; abc++ )); do
        echo "$abc : '${output_array[$abc]}'"
      done
    fi
   
}

REVERSE() {
    
    local haystack="$1"
    local delimiter="$2"
    local result=""
    
    if [ -z "$haystack" ]; then
        return 0
    fi
    
    if [ -z "$delimiter" ]; then
        # CHARACTER MODE: reverse elk karakter
        local len=${#haystack}
        for ((i=len-1; i>=0; i--)); do
            result+="${haystack:$i:1}"
        done
    else
        # TOKEN MODE: reverse tokens
      
        # Split op delimiter 
        MAPFILE "$haystack" "$delimiter" "fields"
        
        # Bouw resultaat in omgekeerde volgorde
        for ((abc=${#fields[@]}; abc>=1; abc--)); do
            if [ -n "$result" ]; then
                result+="$delimiter"
            fi
            result+="${fields[$abc]}"
        done
    fi
    
    echo "$result"
    
}

# MAIN 
args=()

#
# Check voor pipe input
if read -t 0.01 -r -n 1 eerste_karakter; then
    # Er is daadwerkelijk data. Lees de rest, voeg de marker toe en knip 'm er weer af. (grab the newline)
    rest=$(cat; echo "$stopper")
    stdin_content="${eerste_karakter}${rest}"
    # Verwijder marker + eventuele newline
    stdin_content="${stdin_content%$stopper}"
    stdin_content="${stdin_content%$'\n'}"
    # we willen "" ook vangen.
    # if [ -n "$stdin_content" ]; then
        args+=("$stdin_content")
    # fi
# else
  # # pipe or file
  # # bacon (en anderen) openen een pipe intern. beiden (-p en -f ) reageren daarop.
  # if [ -p /dev/stdin ] || [ -f /dev/stdin ] ; then
  #   stdin_content=$(cat; echo "$stopper")
  #   stdin_content="${stdin_content%$stopper}"
  #   stdin_content="${stdin_content%$'\n'}"
  #   # we willen "" ook vangen.
  #   # if [ -n "$stdin_content" ]; then
  #       args+=("$stdin_content")
  #   # fi
 #  fi
fi

debug=""
endofoptions=""
for arg in "$@"; do

    case "$arg" in
        
        -h|--help)
            
            if [ -z "$endofoptions" ]; then
              show_usage
              exit 0
            fi
            args+=("$arg")
            ;;
        
        -v|--version)
            if [ -z "$endofoptions" ]; then
              echo "$VERSION"
              exit 0
            fi
            args+=("$arg")
            ;;
           
        -d|--debug)
            if [ -z "$endofoptions" ]; then
              debug="1"
            else
              args+=("$arg")
            fi
            ;;
        
        --)
            if [ -z "$endofoptions" ]; then
              shift
              endofoptions="1" 
              endofoptionstoggle="1"
            else
              args+=("$arg")
            fi
            ;;
                
    #    -*)
    #        # what about a megative number ?
    #        if [ -z "$endofoptions" ]; then
    #          args+=("$arg")
    #        else
    #          echo "$MYBASENAME: Unknown option $arg" >&2
    #          exit 123
    #        fi
    #        ;;
          
        *) 
            args+=("$arg")
            ;;
    esac
    
done

# Valideer aantal argumenten
if [ "${#args[@]}" -lt 1 ]; then
    echo "$MYBASENAME: Need at least text" >&2
    exit 123
fi

if [ "${#args[@]}" -gt 2 ]; then
    echo "$MYBASENAME: Too many arguments" >&2
    exit 123
fi

# Roep REVERSE aan
REVERSE "${args[@]}"
exit $?
