#!/bin/bash

VERSION="0.20.9"
MYBASENAME=$(basename "$0")

char1=$'\x01'
char2=$'\x02'
char3=$'\x03'
stopper="${char1}${char2}${char3}${char2}${char1}"

show_usage() {
    cat << EOF

Usage: $MYBASENAME <text> <amount>

Returns the last amount of characters from the right side of a text string.
If amount is negative, returns all but the first n characters.

Parameters:
  text        - The string to extract from (can be passed via pipe)
  n           - Number of characters to extract:
                 positive: take last n characters
                 negative: remove first n characters
                 zero: returns empty string

Examples:
  $MYBASENAME "Hello world" 5          # -> world
  $MYBASENAME "Hello world" -5         # -> world (removes first 5)
  echo "Hello world" | $MYBASENAME 5
  $MYBASENAME "Hello" 10               # -> Hello (whole string if n > length)

Options:
  -h, --help           Show this help message
  -v, --version        Show version information
  
  in case you want --help, --version or -- itself as an argument:
  --                   End of options 
          
;°)
  
EOF
}

# check only voor verbose & debug first.
verbose=""
debug=""
for arg in "$@"; do
    [ "$arg" = "--" ] && break
    if [ "$arg" = "--verbose" ]; then
        verbose=1
        break
    fi
    if [ "$arg" = "--debug" ]; then
        set -x
        break
    fi
done

RIGHT() {
    local string="$1"
    local n="$2"
    
    # Validatie: n moet een getal zijn
    if [[ ! "$n" =~ ^-?[0-9]+$ ]]; then
        echo "$MYBASENAME: amount must be an integer" >&2
        return 123
    fi
    
    local result=""
    
    if [ "$n" -ge 0 ]; then
        # Positief: laatste n karakters
        if [ "$n" -ge ${#string} ]; then
            result="$string"
        else
            result="${string: -$n}"
        fi
    else
        # Negatief: verwijder eerste |n| karakters
        local remove=$(( -n ))
        if [ "$remove" -ge ${#string} ]; then
            result=""
        else
            result="${string:$remove}"
        fi
    fi
    
    # Alleen output als resultaat niet leeg is
    if [ -n "$result" ]; then
        echo "$result"
    fi
}

# MAIN 
args=()

#
# Check voor pipe input
if IFS='' read -t 0.01 -r -n 1 eerste_karakter; then
    # Er is daadwerkelijk data. Lees de rest, voeg de marker toe en knip 'm er weer af. (grab the newline)
    rest=$(cat; echo "$stopper")
    stdin_content="${eerste_karakter}${rest}"
    # Verwijder marker + eventuele newline
    stdin_content="${stdin_content%$stopper}"
    stdin_content="${stdin_content%$'\n'}"
    # we willen "" ook vangen.
    # if [ -n "$stdin_content" ]; then
        args+=("$stdin_content")
    # fi
# else
  # # pipe or file
  # # bacon (en anderen) openen een pipe intern. beiden (-p en -f ) reageren daarop.
  # if [ -p /dev/stdin ] || [ -f /dev/stdin ] ; then
  #   stdin_content=$(cat; echo "$stopper")
  #   stdin_content="${stdin_content%$stopper}"
  #   stdin_content="${stdin_content%$'\n'}"
  #   # we willen "" ook vangen.
  #   # if [ -n "$stdin_content" ]; then
  #       args+=("$stdin_content")
  #   # fi
 #  fi
fi

[ -n "$verbose" ] && echo
endofoptions=""
for arg in "$@"; do
   
    [ -n "$verbose" ] && echo "arg : $arg"
    
    case "$arg" in
        
        -h|--help)
            
            if [ -z "$endofoptions" ]; then
              show_usage
              exit 0
            fi
            args+=("$arg")
            ;;
        
        -v|--version)
            if [ -z "$endofoptions" ]; then
              echo "$VERSION"
              exit 0
            fi
            args+=("$arg")
            ;;
        
        -v|--verbose|-d|--debug)
        
           if [ -z "$endofoptions" ]; then args+=("$arg") ; fi
           ;;
            
        --)
            if [ -z "$endofoptions" ]; then
              shift
              endofoptions="1" 
              endofoptionstoggle="1"
            else
              args+=("$arg")
            fi
            ;;
                
    #    -*)
    #        # what about a megative number ?
    #        if [ -z "$endofoptions" ]; then
    #          args+=("$arg")
    #        else
    #          echo "$MYBASENAME: Unknown option $arg" >&2
    #          exit 123
    #        fi
    #        ;;
          
        *) 
            args+=("$arg")
            ;;
    esac
    
done

# Valideer aantal argumenten
if [ "${#args[@]}" -lt 2 ]; then
    echo "$MYBASENAME: Need at least text and n" >&2
    exit 123
fi

if [ "${#args[@]}" -gt 2 ]; then
    echo "$MYBASENAME: Too many arguments" >&2
    exit 123
fi

RIGHT "${args[@]}"
exit $?
