#!/bin/bash

VERSION="0.20.4"
MYBASENAME=$(basename "$0")

char1=$'\x01'
char2=$'\x02'
char3=$'\x03'
stopper="${char1}${char2}${char3}${char2}${char1}"

show_usage() {
    cat << EOF

Usage: $MYBASENAME <text> <start> <length>

Removes a substring starting at position with given length.
Returns everything EXCEPT that substring.
Negative values count from the end.

Parameters:
  text        - The string to modify (can be passed via pipe)
  start       - Start position (1 = first, -1 = last)
  length      - Number of characters to remove:
                 positive = remove characters to the right
                 negative = remove characters to the left

Examples:
  $MYBASENAME "blablabla" 2 3        # -> blabla (remove "lab" from pos 2)
  $MYBASENAME "blablabla" -2 -3      # -> labla (remove "abl" from pos -2 to left)
  $MYBASENAME "Hello world" 4 5      # -> Helrld (remove "lo wo")
  $MYBASENAME "Hello world" -5 3     # -> Hello rld (remove "wor")
  $MYBASENAME "Hello world" 3 -2     # -> Helloworld (remove "ll")

Options:
  -h, --help           Show this help message
  -v, --version        Show version information
  
  in case you want --help, --version or -- itself as an argument:
  --                   End of options 
          
;°)
  
EOF
}

RIP() {
    local string="$1"
    local start="$2"
    local length="$3"
    local len=${#string}
    local result=""
    
    # Validatie
    if [[ ! "$start" =~ ^-?[0-9]+$ ]] || [[ ! "$length" =~ ^-?[0-9]+$ ]]; then
        echo "$MYBASENAME: start and length must be integers" >&2
        return 123
    fi
    
    # Converteer start naar 0-based index
    if [ "$start" -gt 0 ]; then
        start=$((start - 1))
    elif [ "$start" -lt 0 ]; then
        start=$((len + start))
    else
        # start == 0 is invalid (1-based counting starts at 1)
        return 1
    fi
    
    # Check of start binnen bereik is
    if [ "$start" -lt 0 ] || [ "$start" -ge "$len" ]; then
        echo "$string"  # Buiten bereik, niets te verwijderen
        return
    fi
    
    # Bereken te verwijderen segment
    local remove_start="$start"
    local remove_end
    
    if [ "$length" -gt 0 ]; then
        # Positieve lengte: verwijder naar rechts
        remove_end=$((start + length))
    elif [ "$length" -lt 0 ]; then
        # Negatieve lengte: verwijder naar links
        remove_start=$((start + length + 1))
        remove_end=$((start + 1))
    else
        # length == 0: niets verwijderen
        echo "$string"
        return
    fi
    
    # Zorg dat remove_start en remove_end binnen bereik blijven
    [ "$remove_start" -lt 0 ] && remove_start=0
    [ "$remove_end" -gt "$len" ] && remove_end=$len
    
    # Bouw resultaat: deel VOOR remove_start + deel NA remove_end
    if [ "$remove_start" -gt 0 ]; then
        result+="${string:0:$remove_start}"
    fi
    
    if [ "$remove_end" -lt "$len" ]; then
        result+="${string:$remove_end}"
    fi
    
    # Alleen output als resultaat niet leeg is
    if [ -n "$result" ]; then
        echo "$result"
    fi
}

# MAIN 
args=()

#
# Check voor pipe input
if read -t 0.01 -r -n 1 eerste_karakter; then
    # Er is daadwerkelijk data. Lees de rest, voeg de marker toe en knip 'm er weer af. (grab the newline)
    rest=$(cat; echo "$stopper")
    stdin_content="${eerste_karakter}${rest}"
    # Verwijder marker + eventuele newline
    stdin_content="${stdin_content%$stopper}"
    stdin_content="${stdin_content%$'\n'}"
    # we willen "" ook vangen.
    # if [ -n "$stdin_content" ]; then
        args+=("$stdin_content")
    # fi
# else
  # # pipe or file
  # # bacon (en anderen) openen een pipe intern. beiden (-p en -f ) reageren daarop.
  # if [ -p /dev/stdin ] || [ -f /dev/stdin ] ; then
  #   stdin_content=$(cat; echo "$stopper")
  #   stdin_content="${stdin_content%$stopper}"
  #   stdin_content="${stdin_content%$'\n'}"
  #   # we willen "" ook vangen.
  #   # if [ -n "$stdin_content" ]; then
  #       args+=("$stdin_content")
  #   # fi
 #  fi
fi

debug=""
endofoptions=""
for arg in "$@"; do

    case "$arg" in
        
        -h|--help)
            
            if [ -z "$endofoptions" ]; then
              show_usage
              exit 0
            fi
            args+=("$arg")
            ;;
        
        -v|--version)
            if [ -z "$endofoptions" ]; then
              echo "$VERSION"
              exit 0
            fi
            args+=("$arg")
            ;;
           
        -d|--debug)
            if [ -z "$endofoptions" ]; then
              debug="1"
            else
              args+=("$arg")
            fi
            ;;
        
        --)
            if [ -z "$endofoptions" ]; then
              shift
              endofoptions="1" 
              endofoptionstoggle="1"
            else
              args+=("$arg")
            fi
            ;;
                
    #    -*)
    #        # what about a megative number ?
    #        if [ -z "$endofoptions" ]; then
    #          args+=("$arg")
    #        else
    #          echo "$MYBASENAME: Unknown option $arg" >&2
    #          exit 123
    #        fi
    #        ;;
          
        *) 
            args+=("$arg")
            ;;
    esac
    
done

# Valideer aantal argumenten
if [ "${#args[@]}" -lt 3 ]; then
    echo "$MYBASENAME: Need text, start position, and length" >&2
    show_usage
    exit 1
fi

if [ "${#args[@]}" -gt 3 ]; then
    echo "$MYBASENAME: Too many arguments" >&2
    show_usage
    exit 1
fi

RIP "${args[@]}"
exit $?
