#!/bin/bash

VERSION="0.20.8"
MYBASENAME=$(basename "$0")

char1=$'\x01'
char2=$'\x02'
char3=$'\x03'
stopper="${char1}${char2}${char3}${char2}${char1}"

show_usage() {
    cat << EOF

Usage: $MYBASENAME <haystack> <needle> [<position>]

Counts how many times <needle> occurs in <haystack>,
optionally starting at <position>.

Parameters:
  text        - The string to search in (can be passed via pipe)
  needle      - What to count
  position    - from where to count, negative is couting from the end
  
Examples:
  $MYBASENAME "bla bla bla" "bla"           # -> 3 
  $MYBASENAME "blabla bla bla" "bla"        # -> 4 
  echo "a,b,c,a,b,c" | $MYBASENAME "a"      # -> 2 
  echo "a,b,c,aa,b,c" | $MYBASENAME "a"     # -> 3 
  echo "aaa" | $MYBASENAME "a"              # -> 2 

Options:
  -h, --help           Show this help message
  -v, --version        Show version information
  
  in case you want --help, --version or -- itself as an argument:
  --                   End of options 
          
;°)
  
EOF
}

# check only voor verbose & debug first.
verbose=""
debug=""
for arg in "$@"; do
    [ "$arg" = "--" ] && break
    if [ "$arg" = "--verbose" ]; then
        verbose=1
        break
    fi
    if [ "$arg" = "--debug" ]; then
        set -x
        break
    fi
done

TALLY() {
    
    local haystack="$1"
    local needle="$2"
    local position="${3:-1}"
    local count=0
    
    if [ "$position" -gt "0" ] ; then
      position=$(( position-1 ))
    else
      if [ "$position" -lt "0" ] ; then
        len="${#haystack}"
        position=$(( len + position  ))
      else
        echo "position can not be 0."  >&2
        return 123
      fi
    fi
    
    if [ "$position" != "0" ] ; then
          haystack="${haystack:$position}"
    fi
    
    # Tel ALLE voorkomens van substring
    local temp="$haystack"
    while [[ "$temp" == *"$needle"* ]]; do
        ((count++))
        temp="${temp#*"$needle"}"
    done
     
    echo "$count"
    
}

# MAIN 
args=()

#
# Check voor pipe input
if IFS='' read -t 0.01 -r -n 1 eerste_karakter; then
    # Er is daadwerkelijk data. Lees de rest, voeg de marker toe en knip 'm er weer af. (grab the newline)
    rest=$(cat; echo "$stopper")
    stdin_content="${eerste_karakter}${rest}"
    # Verwijder marker + eventuele newline
    stdin_content="${stdin_content%$stopper}"
    stdin_content="${stdin_content%$'\n'}"
    # we willen "" ook vangen.
    # if [ -n "$stdin_content" ]; then
        args+=("$stdin_content")
    # fi
# else
  # # pipe or file
  # # bacon (en anderen) openen een pipe intern. beiden (-p en -f ) reageren daarop.
  # if [ -p /dev/stdin ] || [ -f /dev/stdin ] ; then
  #   stdin_content=$(cat; echo "$stopper")
  #   stdin_content="${stdin_content%$stopper}"
  #   stdin_content="${stdin_content%$'\n'}"
  #   # we willen "" ook vangen.
  #   # if [ -n "$stdin_content" ]; then
  #       args+=("$stdin_content")
  #   # fi
 #  fi
fi

[ -n "$verbose" ] && echo
endofoptions=""
for arg in "$@"; do
   
    [ -n "$verbose" ] && echo "arg : $arg"
    
    case "$arg" in
        
        -h|--help)
            
            if [ -z "$endofoptions" ]; then
              show_usage
              exit 0
            fi
            args+=("$arg")
            ;;
        
        -v|--version)
            if [ -z "$endofoptions" ]; then
              echo "$VERSION"
              exit 0
            fi
            args+=("$arg")
            ;;
        
        -v|--verbose|-d|--debug)
        
           if NOT ISNULL "$endofoptions"; then args+=("$arg") ; fi
           ;;
            
        --)
            if [ -z "$endofoptions" ]; then
              shift
              endofoptions="1" 
              endofoptionstoggle="1"
            else
              args+=("$arg")
            fi
            ;;
                
    #    -*)
    #        # what about a megative number ?
    #        if [ -z "$endofoptions" ]; then
    #          args+=("$arg")
    #        else
    #          echo "$MYBASENAME: Unknown option $arg" >&2
    #          exit 123
    #        fi
    #        ;;
          
        *) 
            args+=("$arg")
            ;;
    esac
    
done

# Valideer aantal argumenten
if [ "${#args[@]}" -lt 2 ]; then
    echo "$MYBASENAME: Need at least haystack and needle" >&2
    # show_usage
    exit 123
fi

if [ "${#args[@]}" -gt 3 ]; then
    echo "$MYBASENAME: Too many arguments" >&2
    # show_usage
    exit 123
fi

TALLY "${args[@]}"
exit $?
